## **Label Encoding**

Label and Ordinal Encoding are two techniques used to encode categorical data as numerical data.

In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

In [2]:
## Creating a DataFrame
df = pd.DataFrame({
    'color' : ['red', 'blue', 'green', 'green', 'red', 'blue']
})
df

color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [4]:
lb = LabelEncoder()
ode = OrdinalEncoder()

In [6]:
df_lb = lb.fit_transform(df[['color']])
df_lb

c:\Users\singh\OneDrive\Desktop\Data-Science\DataScienceEnv\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 2, 0])

In [7]:
lb.transform([['red']])

c:\Users\singh\OneDrive\Desktop\Data-Science\DataScienceEnv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

In [8]:
lb.transform([['green']])

c:\Users\singh\OneDrive\Desktop\Data-Science\DataScienceEnv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([1])

In [9]:
lb.transform([['blue']])

c:\Users\singh\OneDrive\Desktop\Data-Science\DataScienceEnv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([0])

## Ordinal Encoding

It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value based on its position in the order.

In [10]:
df = pd.DataFrame({
    'size' : ['small', 'medium', 'large', 'medium', 'small', 'large']
})
df

size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [12]:
od = OrdinalEncoder(categories= [['small', 'medium', 'large']])

In [13]:
df_od = od.fit_transform(df[['size']])

In [15]:
df_new = pd.DataFrame(df_od, columns = df.columns)
df_new

size
0   0.0
1   1.0
2   2.0
3   1.0
4   0.0
5   2.0