## Logistic Regression for Multiclass Classification Problem

In [1]:
## Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Importing Dataset
from sklearn.datasets import load_breast_cancer
from sklearn.datasets import make_classification

## Importing Algorithms
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

%matplotlib inline

In [4]:
## Creating Dataset
x, y = make_classification(n_samples=1000, n_features=10, n_informative=3,n_classes=3, random_state=42)

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.30, random_state=42)

In [11]:
logistic = LogisticRegression()
logistic.fit(x_train, y_train)
y_pred = logistic.predict(x_test)

In [12]:
score = accuracy_score(y_test, y_pred)
print("Accuracy Score: ",score)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix: \n", cm)

cr = classification_report(y_test, y_pred)
print("Classification Report \n", cr)

Accuracy Score:  0.7033333333333334
Confusion Matrix: 
 [[76 20  7]
 [25 48 23]
 [ 2 12 87]]
Classification Report 
               precision    recall  f1-score   support

           0       0.74      0.74      0.74       103
           1       0.60      0.50      0.55        96
           2       0.74      0.86      0.80       101

    accuracy                           0.70       300
   macro avg       0.69      0.70      0.69       300
weighted avg       0.70      0.70      0.70       300

